# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomation', '0002_auto_20180731_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attitude',
            field=models.IntegerField(choices=[(-1, '反对'), (0, ''), (1, '赞成')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Redact', 'Redact'), ('Manage', 'Manage')], default='Normal', max_length=6),
        ),
    ]
